const PERMISSIONS = {
  DASHBOARD: 1,
  UPDATE: 2,
  USER_PROFILE: 3,

  CANCEL_TXN: 10,
  CREATE_INVOICE: 11,
  CREATE_REDEMPTION: 12,
  REDEMPTION_INFO: 13,
  PRICING: 14,

  GOLD_REDEMPTION: 20,
  GOLD_SELL: 21,
  GOLD_REVOKE_MANDATE: 22,
  GOLD_DEPOSIT: 23,
  GOLD_WITHDRAW: 24,
  GOLD_OFFERS: 25,

  SILVER_REDEMPTION: 30,
  SILVER_SELL: 31,
  SILVER_REVOKE_MANDATE: 32,
  SILVER_DEPOSIT: 33,
  SILVER_WITHDRAW: 34,
  SILVER_OFFERS: 35,

  CONFIG: 40,
  USERS: 41,
  WALLET: 42,
  MANDATE: 43,

  BLOCK_USERS: 50,
  BLOCK_UPIS: 51,

  JEWELLERY: 60,
  SETTINGS: 61,
  OFFERS: 62,
} as const;



export default PERMISSIONS;